### PR TITLE
Add #!/bin/bash in start.sh

### PR DESCRIPTION
**Pull request by kigawas**

### CODE REVIEW

**Comment by kigawas** [comment]
```
Run romeovs/lcov-reporter-action@v0.2.16
RequestError [HttpError]: Resource not accessible by integration
```

CI needs to be fixed

**Comment by bmcd87** [comment]
Good catch! We should definitely put this on all of the shell scripts.

Please follow the instructions here to send us a CLA so we can accept the change:
https://github.com/jpmorganchase/cla

Thanks!

**Comment by kigawas** [comment]
CLA sent

**Comment by fixanoid** [comment]
CLA received. Thank you!

**Pull request merged**
